config { type: "table" }

SELECT
	TRIM(REGEXP_EXTRACT(j.job_name, r"- (.*)\(")) as job_name,
	j.qb_name,
	s.scheduled_item,
	s.scheduled_end,
	s.completed,
        ${model_mapping.model_mapping("s.model")} as model,
	s.assigned_to
FROM
	${ref("buildertrend_billing_jobsites_clean")} j
LEFT JOIN
	${ref("buildertrend_billing_schedule_clean")} s
ON
	j.job_name = s.job_name
WHERE
	j.job_name != "ZZ Test"

